public enum MenuOption
{
    InitJCM = 1,
    InitMEI,
    ShutdownDevice,
    EnterJCMMenu,
    EnterMEIMenu,
    StatusRequest = 17,
    FromPowerOnToIdling = 33,
    AcceptingBillStack1,
    ProgramSignatureTest,
    Reset = 64,
    Stack1,
    Stack2,
    Return,
    Hold,
    Wait,
    Acknowledge = 80,
    EnableDisableRequest = 128,
    SecurityRequest,
    CommunicationModeRequest,
    InhibitRequest,
    DirectionRequest,
    OptionalFunctionRequest,
    BarcodeFunctionRequest,
    BarInhibitRequest,
    VersionRequest,
    BootVersionRequest,
    CurrencyAssignmentRequest,
    SerialNumber = 145,
    EnableDisable = 192,
    Security,
    CommunicationMode,
    Inhibit,
    Direction,
    OptionalFunction,
    BarcodeFunction,
    BarInhibit,
    ProgramSignature = 220,
    ToggleTimeMeasuring = 254,
    EnableInterrupts,
    MEI_EXT_QueryExtendedNoteSpecification = 302,
    MEI_EXT_InitializeExtendedCFSC,
    MEI_EXT_SetEscrowTimeout,
    MEI_EXT_SetAssetNumber,
    MEI_EXT_QueryValueTable,
    MEI_EXT_NotRetrieved = 311,
    MEI_EXT_AdvancedBookmarkMode = 313,
    MEI_EXT_RequestRecyclerNoteTable = 319,
    MEI_EXT_SetRecyclerNoteValueEnable,
    MEI_EXT_RecyclerOmnibusCommandReply,
    MEI_EXT_DispenseBill,
    MEI_EXT_CancelDispense,
    MEI_EXT_FloatBill,
    MEI_EXT_LastCashMovementSummaryReport,
    MEI_EXT_MissingNoteReport,
    MEI_EXT_RequestPhysicalRecyclerStatus,
    MEI_EXT_ClearAuditDataRequest = 329,
    MEI_EXT_EscrowSessionSummaryReport = 332,
    MEI_EXT_TransfertNotes,
    MEI_EXT_RequestPhysicalRecyclerOrderedContent,
    MEI_EXT_PerformRSCommand,
    MEI_EXT_DispenseClassifiedBills,
    MEI_EXT_FloatClassifiedBills,
    MEI_EXT_ClassifiedBanknotesEscrowSessionSummaryReport,
    MEI_EXT_RequestPhysicalClassifiedBanknotesOrderedContent,
    MEI_EXT_CashboxCleanliness = 444,
    Quit = 1024,
    MEI_StdHostToAcceptorMsg = 4016,
    MEI_Denomination = 4161,
    MEI_InterruptMode,
    MEI_Security,
    MEI_Orientation,
    MEI_Escrow,
    MEI_PushMode,
    MEI_BarcodeDecoding,
    MEI_Powerup,
    MEI_SetExtendedNoteReporting,
    MEI_SetExtendedCouponReporting,
    MEI_Stack = 4177,
    MEI_Return,
    MEI_ClearCashboxTotals,
    MEI_SoftReset,
    MEI_QuerySwCRC = 4192,
    MEI_QueryCashValueInCassette,
    MEI_QueryNumberOfAcceptorResets,
    MEI_QueryAcceptorType = 4196,
    MEI_QueryAcceptorSerial,
    MEI_QueryAcceptorBootPartNumber,
    MEI_QueryAcceptorApplicationPartNumber,
    MEI_QueryAcceptorVariantName,
    MEI_QueryAcceptorVariantPartNumber,
    MEI_QueryAcceptorAuditLifetimeTotals,
    MEI_QueryAcceptorAuditQPMeasures,
    MEI_QueryAcceptorAuditGeneralPerfMeasures,
    MEI_QueryDeviceCapabilities,
    MEI_QueryAcceptorAppId,
    MEI_QueryAcceptorVariantId,
    MEI_QueryBNFStatus,
    MEI_SetBezel = 4209,
    MEI_QueryAcceptorAuditLifetimeTotalsExtended = 4210,
    MEI_QueryAcceptorAuditQPMeasuresExtended,
    MEI_QueryAcceptorAuditPerfMeasuresExtended,
    MEI_QueryAcceptorAuditTotalDocumentsReportingStructure = 4214,
    MEI_QueryAcceptorAuditTotalDocumentsRecognized,
    MEI_QueryAcceptorAuditTotalDocumentsValidated,
    MEI_QueryAcceptorAuditTotalDocumentsStacked,
    MEI_QueryAcceptorDiagnosticsSelfTest,
    MEI_QueryAcceptorDiagnosticsSensorData = 4221,
    MEI_InitializeAndPoll = 4224,
    MEI_InitializeExtendedCFSCAndPoll,
    MEI_InitializeExtendedSCAdvScrAndPoll,
    MEI_ChangeDefaultDenominationStructure,
    MEI_ChangeExtendedCFSCDenominationStructure,
    MEI_ChangeExtendedSCADvScrDenominationStructure,
    MEI_ReadDenominationStatus,
    MEI_EnableDisablePolling,
    MEI_ExtendedLoopMessage,
    Back = 10000,
    Invalid
}